// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package goodbye

import (
	"bytes"
	"code.ibanyu.com/server/go/util.git/idl/gen-go/util/thriftutil"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = thriftutil.GoUnusedProtection__

type GoodbyeService interface {
	// Parameters:
	//  - Name
	//  - Ctx
	SayGoodbye(name string, ctx *thriftutil.Context) (r string, err error)
}

type GoodbyeServiceClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewGoodbyeServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *GoodbyeServiceClient {
	return &GoodbyeServiceClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewGoodbyeServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *GoodbyeServiceClient {
	return &GoodbyeServiceClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - Name
//  - Ctx
func (p *GoodbyeServiceClient) SayGoodbye(name string, ctx *thriftutil.Context) (r string, err error) {
	if err = p.sendSayGoodbye(name, ctx); err != nil {
		return
	}
	return p.recvSayGoodbye()
}

func (p *GoodbyeServiceClient) sendSayGoodbye(name string, ctx *thriftutil.Context) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("SayGoodbye", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := SayGoodbyeArgs{
		Name: name,
		Ctx:  ctx,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *GoodbyeServiceClient) recvSayGoodbye() (value string, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	_, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error1 error
		error1, err = error0.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error1
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "SayGoodbye failed: out of sequence response")
		return
	}
	result := SayGoodbyeResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

type GoodbyeServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      GoodbyeService
}

func (p *GoodbyeServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *GoodbyeServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *GoodbyeServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewGoodbyeServiceProcessor(handler GoodbyeService) *GoodbyeServiceProcessor {

	self2 := &GoodbyeServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self2.processorMap["SayGoodbye"] = &goodbyeServiceProcessorSayGoodbye{handler: handler}
	return self2
}

func (p *GoodbyeServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x3.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x3

}

type goodbyeServiceProcessorSayGoodbye struct {
	handler GoodbyeService
}

func (p *goodbyeServiceProcessorSayGoodbye) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := SayGoodbyeArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("SayGoodbye", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := SayGoodbyeResult{}
	var retval string
	var err2 error
	if retval, err2 = p.handler.SayGoodbye(args.Name, args.Ctx); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing SayGoodbye: "+err2.Error())
		oprot.WriteMessageBegin("SayGoodbye", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return true, err2
	} else {
		result.Success = &retval
	}
	if err2 = oprot.WriteMessageBegin("SayGoodbye", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

type SayGoodbyeArgs struct {
	Name string `thrift:"name,1" json:"name"`
	// unused fields # 2 to 9
	Ctx *thriftutil.Context `thrift:"ctx,10" json:"ctx"`
}

func NewSayGoodbyeArgs() *SayGoodbyeArgs {
	return &SayGoodbyeArgs{}
}

func (p *SayGoodbyeArgs) GetName() string {
	return p.Name
}

var SayGoodbyeArgs_Ctx_DEFAULT *thriftutil.Context

func (p *SayGoodbyeArgs) GetCtx() *thriftutil.Context {
	if !p.IsSetCtx() {
		return SayGoodbyeArgs_Ctx_DEFAULT
	}
	return p.Ctx
}
func (p *SayGoodbyeArgs) IsSetCtx() bool {
	return p.Ctx != nil
}

func (p *SayGoodbyeArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 10:
			if err := p.ReadField10(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *SayGoodbyeArgs) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.Name = v
	}
	return nil
}

func (p *SayGoodbyeArgs) ReadField10(iprot thrift.TProtocol) error {
	p.Ctx = &thriftutil.Context{}
	if err := p.Ctx.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Ctx, err)
	}
	return nil
}

func (p *SayGoodbyeArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("SayGoodbye_args"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *SayGoodbyeArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("name", thrift.STRING, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:name: %s", p, err)
	}
	if err := oprot.WriteString(string(p.Name)); err != nil {
		return fmt.Errorf("%T.name (1) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:name: %s", p, err)
	}
	return err
}

func (p *SayGoodbyeArgs) writeField10(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("ctx", thrift.STRUCT, 10); err != nil {
		return fmt.Errorf("%T write field begin error 10:ctx: %s", p, err)
	}
	if err := p.Ctx.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.Ctx, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 10:ctx: %s", p, err)
	}
	return err
}

func (p *SayGoodbyeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SayGoodbyeArgs(%+v)", *p)
}

type SayGoodbyeResult struct {
	Success *string `thrift:"success,0" json:"success"`
}

func NewSayGoodbyeResult() *SayGoodbyeResult {
	return &SayGoodbyeResult{}
}

var SayGoodbyeResult_Success_DEFAULT string

func (p *SayGoodbyeResult) GetSuccess() string {
	if !p.IsSetSuccess() {
		return SayGoodbyeResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *SayGoodbyeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SayGoodbyeResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.ReadField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *SayGoodbyeResult) ReadField0(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 0: %s", err)
	} else {
		p.Success = &v
	}
	return nil
}

func (p *SayGoodbyeResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("SayGoodbye_result"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *SayGoodbyeResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRING, 0); err != nil {
			return fmt.Errorf("%T write field begin error 0:success: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.Success)); err != nil {
			return fmt.Errorf("%T.success (0) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 0:success: %s", p, err)
		}
	}
	return err
}

func (p *SayGoodbyeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SayGoodbyeResult(%+v)", *p)
}
